version: "3"

vars:
  BUILD_DIR: build
  TEST_DIR: test

tasks:
  default:
    deps: [configure, build]

  debug-on:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DCMAKE_BUILD_TYPE=Debug -DDAP_DEBUG=ON

  debug-off:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DCMAKE_BUILD_TYPE=Debug -DDAP_DEBUG=OFF

  configure:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DBUILD_DOCS=OFF -DBUILD_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug

  build:
    deps: [configure]
    cmds:
      - cmake --build {{.BUILD_DIR}}

  docs:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DBUILD_DOCS=ON -DBUILD_TESTING=OFF
      - cmake --build {{.BUILD_DIR}}

  coverage:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DBUILD_DOCS=ON -DBUILD_TESTING=ON -DENABLE_COVERAGE=ON
      - cmake --build {{.BUILD_DIR}}
      - ctest --test-dir {{.BUILD_DIR}} --output-on-failure

  release:
    deps: [clean]
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_DOCS=ON
      - task: build

  clean:
    cmds:
      - rm -rf {{.BUILD_DIR}}/*

  install:
    cmds:
      - cmake --install {{.BUILD_DIR}}

  test:
    deps: [build]
    cmds:
      - ctest --test-dir {{.BUILD_DIR}} --output-on-failure

  benchmark:
    deps: [build]
    cmds:
      - ./build/tests [!benchmark] --benchmark-samples 20

  linpred-benchmark:
    deps: [build]
    cmds:
      - ./build/tests "Linear predictor parallelization" --benchmark-samples 10

  gradient-benchmark:
    deps: [build]
    cmds:
      - ./build/tests "Parallelized gradient computations" --benchmark-samples 10

  update-eigen:
    desc: Fetch and update the latest Eigen library
    vars:
      EIGEN_VERSION:
        sh: curl -s https://gitlab.com/api/v4/projects/libeigen%2Feigen/releases | jq -r '.[0].tag_name'
    cmds:
      - echo "Fetching Eigen {{.EIGEN_VERSION}}..."
      - mkdir -p tmp
      - curl -L https://gitlab.com/libeigen/eigen/-/archive/{{.EIGEN_VERSION}}/eigen-{{.EIGEN_VERSION}}.tar.gz -o tmp/eigen.tar.gz
      - cd tmp && tar xzf eigen.tar.gz
      - rm -rf external/Eigen
      - mkdir -p external
      - cp -r tmp/eigen-*/Eigen external/
      - rm -rf tmp
      - git add external/Eigen
      - 'git commit -m "build(deps): update Eigen to {{.EIGEN_VERSION}}" -m "Source: https://gitlab.com/libeigen/eigen/-/releases/{{.EIGEN_VERSION}}"'
    silent: true
