version: "3"

vars:
  BUILD_DIR: build
  TEST_DIR: test

tasks:
  default:
    deps: [configure, build]

  debug-on:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DCMAKE_BUILD_TYPE=Debug -DDAP_DEBUG=ON

  debug-off:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DCMAKE_BUILD_TYPE=Debug -DDAP_DEBUG=OFF

  configure:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DBUILD_DOCS=OFF -DBUILD_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug

  build:
    deps: [configure]
    cmds:
      - cmake --build {{.BUILD_DIR}}

  docs:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DBUILD_DOCS=ON -DBUILD_TESTING=OFF
      - cmake --build {{.BUILD_DIR}}
      - ctest --test-dir {{.BUILD_DIR}} --output-on-failure

  coverage:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DBUILD_DOCS=ON -DBUILD_TESTING=ON -DENABLE_COVERAGE=ON
      - cmake --build {{.BUILD_DIR}}
      - ctest --test-dir {{.BUILD_DIR}} --output-on-failure

  release:
    deps: [clean]
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_DOCS=ON
      - task: build

  clean:
    cmds:
      - rm -rf {{.BUILD_DIR}}/*

  install:
    cmds:
      - cmake --install {{.BUILD_DIR}}

  test:
    deps: [build]
    cmds:
      - ctest --test-dir {{.BUILD_DIR}} --output-on-failure

  benchmark:
    deps: [build]
    cmds:
      - ./build/tests [!benchmark] --benchmark-samples 20
