add_test( [==[OLS on small dense matrix without intercept]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[OLS on small dense matrix without intercept]==]  )
set_tests_properties( [==[OLS on small dense matrix without intercept]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[OLS on small dense matrix with intercept]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[OLS on small dense matrix with intercept]==]  )
set_tests_properties( [==[OLS on small dense matrix with intercept]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[OLS on small sparse matrix with intercept]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[OLS on small sparse matrix with intercept]==]  )
set_tests_properties( [==[OLS on small sparse matrix with intercept]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[estimateNoise basic functionality]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[estimateNoise basic functionality]==]  )
set_tests_properties( [==[estimateNoise basic functionality]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Alpha estimation for n >= p + 30]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Alpha estimation for n >= p + 30]==]  )
set_tests_properties( [==[Alpha estimation for n >= p + 30]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Alpha estimation for n < p + 30]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Alpha estimation for n < p + 30]==]  )
set_tests_properties( [==[Alpha estimation for n < p + 30]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[estimateAlpha error handling]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[estimateAlpha error handling]==]  )
set_tests_properties( [==[estimateAlpha error handling]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Full fit with estimate alpha]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Full fit with estimate alpha]==]  )
set_tests_properties( [==[Full fit with estimate alpha]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Full fit with estimate alpha using sparse matrix]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Full fit with estimate alpha using sparse matrix]==]  )
set_tests_properties( [==[Full fit with estimate alpha using sparse matrix]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Interactive alpha estimations]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Interactive alpha estimations]==]  )
set_tests_properties( [==[Interactive alpha estimations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Assertions /home/runner/work/libslope/libslope/_codeql_build_dir/tests Assertions  )
set_tests_properties( Assertions PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Clusters /home/runner/work/libslope/libslope/_codeql_build_dir/tests Clusters  )
set_tests_properties( Clusters PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Pattern matrix]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Pattern matrix]==]  )
set_tests_properties( [==[Pattern matrix]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Cross-validation /home/runner/work/libslope/libslope/_codeql_build_dir/tests Cross-validation  )
set_tests_properties( Cross-validation PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Repeated cross-validation]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Repeated cross-validation]==]  )
set_tests_properties( [==[Repeated cross-validation]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Cross-validation: user folds]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Cross-validation: user folds]==]  )
set_tests_properties( [==[Cross-validation: user folds]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Cross-validation: user folds]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Cross-validation: user folds]==]  )
set_tests_properties( [==[Cross-validation: user folds]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Cross-validation: do not copy x]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Cross-validation: do not copy x]==]  )
set_tests_properties( [==[Cross-validation: do not copy x]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Best alpha index is within bounds]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Best alpha index is within bounds]==]  )
set_tests_properties( [==[Best alpha index is within bounds]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Cluster gradient and Hessian computation]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Cluster gradient and Hessian computation]==]  )
set_tests_properties( [==[Cluster gradient and Hessian computation]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Randomized CD]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Randomized CD]==]  )
set_tests_properties( [==[Randomized CD]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Interrupt callback]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Interrupt callback]==]  )
set_tests_properties( [==[Interrupt callback]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Test that regularization sequence generation works]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Test that regularization sequence generation works]==]  )
set_tests_properties( [==[Test that regularization sequence generation works]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[WarningLogger basic functionality]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[WarningLogger basic functionality]==]  )
set_tests_properties( [==[WarningLogger basic functionality]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[WarningLogger with multiple threads]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[WarningLogger with multiple threads]==]  )
set_tests_properties( [==[WarningLogger with multiple threads]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Logistic, simple fixed design]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Logistic\, simple fixed design]==]  )
set_tests_properties( [==[Logistic, simple fixed design]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Logistic path]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Logistic path]==]  )
set_tests_properties( [==[Logistic path]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Logistic predictions]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Logistic predictions]==]  )
set_tests_properties( [==[Logistic predictions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Failing example (at one point)]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Failing example (at one point)]==]  )
set_tests_properties( [==[Failing example (at one point)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Quadratic with Eigen::Map]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Quadratic with Eigen::Map]==]  )
set_tests_properties( [==[Quadratic with Eigen::Map]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Linear predictor computations]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Linear predictor computations]==]  )
set_tests_properties( [==[Linear predictor computations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Gradient computations]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Gradient computations]==]  )
set_tests_properties( [==[Gradient computations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Gradient offset calculations]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Gradient offset calculations]==]  )
set_tests_properties( [==[Gradient offset calculations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( logSumExp /home/runner/work/libslope/libslope/_codeql_build_dir/tests logSumExp  )
set_tests_properties( logSumExp PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( softmax /home/runner/work/libslope/libslope/_codeql_build_dir/tests softmax  )
set_tests_properties( softmax PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[whichBest function works correctly]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[whichBest function works correctly]==]  )
set_tests_properties( [==[whichBest function works correctly]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Multinomial, unpenalized]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Multinomial\, unpenalized]==]  )
set_tests_properties( [==[Multinomial, unpenalized]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Multinomial wine data]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Multinomial wine data]==]  )
set_tests_properties( [==[Multinomial wine data]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Multinomial predictions]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Multinomial predictions]==]  )
set_tests_properties( [==[Multinomial predictions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Multinomial alternative response types]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Multinomial alternative response types]==]  )
set_tests_properties( [==[Multinomial alternative response types]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Normalization, check solutions]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Normalization\, check solutions]==]  )
set_tests_properties( [==[Normalization, check solutions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Normalization, JIT]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Normalization\, JIT]==]  )
set_tests_properties( [==[Normalization, JIT]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Normalization, JIT modify-X]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Normalization\, JIT modify-X]==]  )
set_tests_properties( [==[Normalization, JIT modify-X]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Normalization, loop combinations]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Normalization\, loop combinations]==]  )
set_tests_properties( [==[Normalization, loop combinations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Path fitting]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Path fitting]==]  )
set_tests_properties( [==[Path fitting]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Poisson models]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Poisson models]==]  )
set_tests_properties( [==[Poisson models]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Poisson abalone data]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Poisson abalone data]==]  )
set_tests_properties( [==[Poisson abalone data]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Poisson predictions]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Poisson predictions]==]  )
set_tests_properties( [==[Poisson predictions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Poisson low regularization]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Poisson low regularization]==]  )
set_tests_properties( [==[Poisson low regularization]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Poisson sparse and dense methods agree]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Poisson sparse and dense methods agree]==]  )
set_tests_properties( [==[Poisson sparse and dense methods agree]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Predictions /home/runner/work/libslope/libslope/_codeql_build_dir/tests Predictions  )
set_tests_properties( Predictions PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Check that proximal operator works]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Check that proximal operator works]==]  )
set_tests_properties( [==[Check that proximal operator works]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Check that normal quantile algorithm works]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Check that normal quantile algorithm works]==]  )
set_tests_properties( [==[Check that normal quantile algorithm works]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Guassian, simple design]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Guassian\, simple design]==]  )
set_tests_properties( [==[Guassian, simple design]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Quadratic, X is identity]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Quadratic\, X is identity]==]  )
set_tests_properties( [==[Quadratic, X is identity]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Quadratic, automatic lambda and alpha]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Quadratic\, automatic lambda and alpha]==]  )
set_tests_properties( [==[Quadratic, automatic lambda and alpha]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Quadratic, various models]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Quadratic\, various models]==]  )
set_tests_properties( [==[Quadratic, various models]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Gaussian parallel]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Gaussian parallel]==]  )
set_tests_properties( [==[Gaussian parallel]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Gaussian predictions]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Gaussian predictions]==]  )
set_tests_properties( [==[Gaussian predictions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Cluster updating]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Cluster updating]==]  )
set_tests_properties( [==[Cluster updating]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Low regularization]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Low regularization]==]  )
set_tests_properties( [==[Low regularization]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Lasso /home/runner/work/libslope/libslope/_codeql_build_dir/tests Lasso  )
set_tests_properties( Lasso PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Abalone dataset]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Abalone dataset]==]  )
set_tests_properties( [==[Abalone dataset]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Relaxed quadratic fits]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Relaxed quadratic fits]==]  )
set_tests_properties( [==[Relaxed quadratic fits]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Orthogonal relaxed path]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Orthogonal relaxed path]==]  )
set_tests_properties( [==[Orthogonal relaxed path]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Relaxed path]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Relaxed path]==]  )
set_tests_properties( [==[Relaxed path]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Mean squared error score]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Mean squared error score]==]  )
set_tests_properties( [==[Mean squared error score]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Mean absolute error score]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Mean absolute error score]==]  )
set_tests_properties( [==[Mean absolute error score]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Accuracy and misclassification]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Accuracy and misclassification]==]  )
set_tests_properties( [==[Accuracy and misclassification]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[ROC AUC score]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[ROC AUC score]==]  )
set_tests_properties( [==[ROC AUC score]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Deviance score]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Deviance score]==]  )
set_tests_properties( [==[Deviance score]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Strong screening rule]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Strong screening rule]==]  )
set_tests_properties( [==[Strong screening rule]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Gaps on screened path]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Gaps on screened path]==]  )
set_tests_properties( [==[Gaps on screened path]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Sparse and dense methods agree]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Sparse and dense methods agree]==]  )
set_tests_properties( [==[Sparse and dense methods agree]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[SlopeThreshold function]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[SlopeThreshold function]==]  )
set_tests_properties( [==[SlopeThreshold function]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Timer /home/runner/work/libslope/libslope/_codeql_build_dir/tests Timer  )
set_tests_properties( Timer PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Subsetting /home/runner/work/libslope/libslope/_codeql_build_dir/tests Subsetting  )
set_tests_properties( Subsetting PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( move_elements /home/runner/work/libslope/libslope/_codeql_build_dir/tests move_elements  )
set_tests_properties( move_elements PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Permutations /home/runner/work/libslope/libslope/_codeql_build_dir/tests Permutations  )
set_tests_properties( Permutations PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Sorting /home/runner/work/libslope/libslope/_codeql_build_dir/tests Sorting  )
set_tests_properties( Sorting PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( Views /home/runner/work/libslope/libslope/_codeql_build_dir/tests Views  )
set_tests_properties( Views PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
add_test( [==[Zero-variance columns]==] /home/runner/work/libslope/libslope/_codeql_build_dir/tests [==[Zero-variance columns]==]  )
set_tests_properties( [==[Zero-variance columns]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/libslope/libslope/_codeql_build_dir)
set( tests_TESTS [==[OLS on small dense matrix without intercept]==] [==[OLS on small dense matrix with intercept]==] [==[OLS on small sparse matrix with intercept]==] [==[estimateNoise basic functionality]==] [==[Alpha estimation for n >= p + 30]==] [==[Alpha estimation for n < p + 30]==] [==[estimateAlpha error handling]==] [==[Full fit with estimate alpha]==] [==[Full fit with estimate alpha using sparse matrix]==] [==[Interactive alpha estimations]==] Assertions Clusters [==[Pattern matrix]==] Cross-validation [==[Repeated cross-validation]==] [==[Cross-validation: user folds]==] [==[Cross-validation: user folds]==] [==[Cross-validation: do not copy x]==] [==[Best alpha index is within bounds]==] [==[Cluster gradient and Hessian computation]==] [==[Randomized CD]==] [==[Interrupt callback]==] [==[Test that regularization sequence generation works]==] [==[WarningLogger basic functionality]==] [==[WarningLogger with multiple threads]==] [==[Logistic, simple fixed design]==] [==[Logistic path]==] [==[Logistic predictions]==] [==[Failing example (at one point)]==] [==[Quadratic with Eigen::Map]==] [==[Linear predictor computations]==] [==[Gradient computations]==] [==[Gradient offset calculations]==] logSumExp softmax [==[whichBest function works correctly]==] [==[Multinomial, unpenalized]==] [==[Multinomial wine data]==] [==[Multinomial predictions]==] [==[Multinomial alternative response types]==] [==[Normalization, check solutions]==] [==[Normalization, JIT]==] [==[Normalization, JIT modify-X]==] [==[Normalization, loop combinations]==] [==[Path fitting]==] [==[Poisson models]==] [==[Poisson abalone data]==] [==[Poisson predictions]==] [==[Poisson low regularization]==] [==[Poisson sparse and dense methods agree]==] Predictions [==[Check that proximal operator works]==] [==[Check that normal quantile algorithm works]==] [==[Guassian, simple design]==] [==[Quadratic, X is identity]==] [==[Quadratic, automatic lambda and alpha]==] [==[Quadratic, various models]==] [==[Gaussian parallel]==] [==[Gaussian predictions]==] [==[Cluster updating]==] [==[Low regularization]==] Lasso [==[Abalone dataset]==] [==[Relaxed quadratic fits]==] [==[Orthogonal relaxed path]==] [==[Relaxed path]==] [==[Mean squared error score]==] [==[Mean absolute error score]==] [==[Accuracy and misclassification]==] [==[ROC AUC score]==] [==[Deviance score]==] [==[Strong screening rule]==] [==[Gaps on screened path]==] [==[Sparse and dense methods agree]==] [==[SlopeThreshold function]==] Timer Subsetting move_elements Permutations Sorting Views [==[Zero-variance columns]==])
