name: build-and-test
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y g++

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.25"

      - name: Configure CMake
        run: cmake -B build -S . -DBUILD_TESTING=ON -DBUILD_DOCS=OFF

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build

      - name: Test
        run: ctest --test-dir build --output-on-failure
